### ISSUE TITLE
Documentation not compiling

### ISSUE THREAD

**Issue by sunilkul1** [iotaap/tutorials#1]
Documentation cannot be compiled, mkdocs thows an error

**Comment by igolubic** [comment]
Our documentation is generated automatically using our Jenkins job, and then deployed to docs.iotaap.io. In order to test and develop docs locally, you have to properly install **mkdocs** and [Material Theme for mkdocs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/). 

Before committing your change and creating the new PR, please check that your documentation compiles, otherwise your changes will be automatically rejected since we run tests before deployment, and your contribution has to be approved by the IoTaaP team. 

Please use our [Community](https://community.iotaap.io/) to discuss any issues with our documentation.
